/**
 * Licensed under the GNU LESSER GENERAL PUBLIC LICENSE, version 2.1, dated February 1999.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the latest version of the GNU Lesser General
 * Public License as published by the Free Software Foundation;
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program (LICENSE.txt); if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * Based on code generated by Agitar build: Agitator Version 1.0.2.000071 (Build date: Jan 12, 2007) [1.0.2.000071]
 */
package org.jamwiki.utils;

import org.jamwiki.JAMWikiUnitTest;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * @deprecated Tiddly wiki import support has been unmaintained since JAMWiki
 *  0.6.0 and will be removed in a future release unless a new maintainer is
 *  found.
 */
public class TiddlyWiki2MediaWikiTranslatorTest extends JAMWikiUnitTest {

	/**
	 *
	 */
	@Test
	public void testWikiLinks() throws Exception {
		TiddlyWiki2MediaWikiTranslator t = new TiddlyWiki2MediaWikiTranslator();
		assertEquals("abc [[WikiLink]] def", t.translate("abc WikiLink def"));
	}
}
